language: python
dist: bionic
sudo : false
addons:
  apt:
    packages:
    - poppler-utils
    - tesseract-ocr
    - tesseract-ocr-eng
    - imagemagick
    - libleptonica-dev
    - libicu-dev
    - libpango1.0-dev
    - libcairo2-dev
python:
  #- "2.7"
  - "3.6"
notifications:
  email: false
#before_install:
#  - pip install pip --upgrade
#  - pip install bibtexparser
#  - pip install six
#  - pip install crossrefapi
#  - pip install fuzzywuzzy
#  - pip install unidecode
#  - pip install scholarly
# test coverage
#  - pip install tox
#  - "python -m pip install --upgrade pip"
#  - "python -m pip install --upgrade pytest pytest-cov coveralls"
  #- pip install coveralls
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - travis_retry conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  #- travis_retry pip install --only-binary=numpy,scipy,pandas numpy nose scipy h5py theano pytest pytest-pep8 pandas --progress-bar off
  - travis_retry conda install scipy cython nose h5py pytest pytest-pep8 pytest-cov
  - pip install bibtexparser
  #- pip install six
  - pip install crossrefapi
  - pip install fuzzywuzzy
  - pip install unidecode
  - pip install scholarly

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
  - python setup.py install

script: py.test -xv --cov papers.bib tests

after-success: coveralls
