language: python
dist: trusty
sudo : false
addons:
  apt:
    packages:
    - poppler-utils
    - tesseract-ocr
    - tesseract-ocr-eng
    - imagemagick
    - libleptonica-dev
    - libicu-dev
    - libpango1.0-dev
    - libcairo2-dev
    - python-tox
python:
  #- "2.7"
  - "3.4"
notifications:
  email: false
before_install:
  - pip install pip --upgrade
  - pip install bibtexparser
  - pip install six
  - pip install crossrefapi
  - pip install fuzzywuzzy
  - pip install unidecode
  - pip install scholarly
  - pip install tox-travis
# test coverage
#  - pip install tox
#  - "python -m pip install --upgrade pip"
#  - "python -m pip install --upgrade pytest pytest-cov coveralls"
  #- pip install coveralls
install:
  - python setup.py install

script: py.test -xv --cov papers.bib tests
#script: tox -e py27 -e py34

after-success: coveralls
